name: Java CI con Maven + Selenium + SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Post Checkout
      uses: actions/checkout@v3

    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/org/openjfx
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Instalar Google Chrome
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    # Instalar ChromeDriver
    - name: Install ChromeDriver
      uses: browser-actions/setup-chromedriver@v1

    # Compilar y testear
    - name: Build & Test (headless)
      run: mvn -Dtest=devops.UsuarioTest,devops.UsuarioSeleniumTest,devops.UsuarioFuncionalTest test

    # Análisis de SonarQube
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
