name: CI DevOps Evaluación Módulo 4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
    # 1) Clonar repo
    - name: Checkout
      uses: actions/checkout@v3

    # 2) JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3) Cache Maven
    - name: Cache Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # 4) Instalar Google Chrome
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    # 5) Instalar Chromedriver que coincida
    - name: Install Chromedriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: 'latest'

    # 6) Ejecutar pruebas (JUnit + Selenium)
    - name: Build & Test (headless)
      env:
        WEBDRIVER_CHROME_DRIVER: ${{ steps.Install_Chromedriver.outputs.chromedriver-path }}
      run: |
        echo "Chromedriver path: $WEBDRIVER_CHROME_DRIVER"
        mvn -B clean test -Dwebdriver.chrome.driver="$WEBDRIVER_CHROME_DRIVER"

    # 7) Análisis SonarQube
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B sonar:sonar \
          -Dsonar.projectKey=eva4-devops \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=$SONAR_TOKEN
