name: Java CI + Selenium + SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Clonar código
    - uses: actions/checkout@v3

    # 2) JDK 17
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3) Caché Maven
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    # 4) Instalar Google Chrome **y** ChromeDriver compatible
    - name: Set up Chrome + ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        install-chromedriver: "true"   # ← aquí instala el driver que coincide

    # 5) Compilar y ejecutar TODAS las pruebas (JUnit + Selenium headless)
    - name: Build & Test
      run: mvn -B clean test

    # 6) Análisis de calidad con SonarQube
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
